---
output: html_document
---

# Matching

I dette kapitel gives en introduktion til, hvordan man gennemfører matching analyser i R.

matching

for introduktionsartikler til matching, se @hoetal2007 og @sekhon2009.

`MatchIt` @hoetal2011.

```{r, warnings=FALSE, message=FALSE}
library("ggplot2")
library("MatchIt")
library("RItools")
```

```{r}
sult <- read.csv("data/petersenetal2014.csv")
```

```{r}
treat.f <- treatment ~ female + ega + income + emp_priv + 
  emp_pub + pubtransfer + preschool
```

```{r}
fit <- glm(treat.f, family=binomial, data=sult)
sult$pscores <- predict(fit, type="response")
```

```{r}
m <- matchit(treat.f, method = "nearest", caliper=.1, data = sult)
m
```

```{r}
m.data <- match.data(m)
```

```{r}
ggplot(sult, aes(x=pscores, linetype=as.factor(treatment), 
                 fill = as.factor(treatment), 
                 colour = as.factor(treatment))) + 
  geom_density(alpha = .1, size = .9) +
  ylab("Densitet") +
  theme_minimal() +
  theme(legend.position="none") +
  scale_x_continuous("", limits=c(0,1))
```

```{r}
ggplot(m.data, aes(x=distance, linetype=as.factor(treatment), 
                   fill = as.factor(treatment), 
                   colour = as.factor(treatment))) + 
  geom_density(alpha = .1, size = .9) +
  ylab("Densitet") +
  theme_minimal() +
  theme(legend.position="none") +
  scale_x_continuous("", limits=c(0,1))
```

```{r}
xB.unmatched <- xBalance(treat.f, data=sult, report=c("all"))
xB.unmatched <- as.data.frame(xB.unmatched)
std.unmatched <- xB.unmatched[,"results.std.diff.unstrat"]
xB.matched <- xBalance(treat.f, data=m.data, report=c("all"))
xB.matched <- as.data.frame(xB.matched)
std.matched <- xB.matched[,"results.std.diff.unstrat"]
balance.df <- data.frame(covariate = row.names(xB.matched), 
                         unmatched=std.unmatched[row.names(xB.unmatched) 
                                                 %in% row.names(xB.matched)], 
                         matched=std.matched)
```

```{r}
ggplot(balance.df, aes(x=covariate, y=unmatched)) + 
  geom_hline(yintercept=0, linetype="dashed", colour="gray50") +
  geom_text(vjust = 1.6, aes(label="U", y=unmatched, size=.9), 
            colour="red", alpha = 0.9) +
  geom_point(aes(y=unmatched, size=.9), colour="red", 
             alpha = 0.6) + 
  geom_text(vjust = 1.6, aes(label="M", y=matched, size=.9), 
            colour="blue", alpha = 0.9) +
  geom_point(aes(y=matched, size=.9), colour="blue", 
             alpha = 0.6) + 
  coord_flip() +
  xlab("Kontrolvariabel") +
  ylab("Standardiseret forskel") +
  theme_minimal() +
  theme(legend.position="none")
```

```{r}
reg.unmatched <- lm(welfare ~ treatment +female + ega + income + 
                      emp_priv + emp_pub + pubtransfer + preschool, 
                    data=sult)
summary(reg.unmatched)
```

```{r}
reg.matched <- lm(welfare ~ treatment + female + ega + income + 
                    emp_priv + emp_pub + pubtransfer + preschool, 
                  data=m.data)
summary(reg.matched)
```